name: learny_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc:
  syncfusion_flutter_pdfviewer:
  chewie: ^1.5.0
  dartz:
  js:
  svg_flutter:
  table_calendar: ^3.0.9
  animated_text_kit: ^4.2.2
  agora_rtc_engine: ^6.2.1
  stream_chat_flutter: ^6.7.0
  stream_chat_localizations:
  responsive_builder:
  webview_flutter:
  permission_handler:
  equatable:
  youtube_player_iframe:
  get_it:
  intl:
  shared_preferences:
  http:
  video_player_web:
  cool_alert:
  awesome_dialog:
  connectivity_plus_web:
  dio:
  flutter_profile_picture: ^2.0.0
  universal_html:
  image_picker_for_web:
  image_picker:
  image_picker_web:
  video_player:
  flutter_screenutil:
  fluttertoast:
  toast:
  flutter_svg: ^2.0.7
  dropdown_button2:
  connectivity_plus:
  google_fonts:
  flutter_rounded_date_picker:
  datetime_picker_formfield_new:
  flutter_localization:
  uuid:
  dotted_border:
  flutter_full_pdf_viewer_null_safe: ^1.0.0
  flutter_time_picker_spinner:
  file_picker:
  file_selector:
  shimmer:
  pin_code_fields:
  googleapis:
  path_provider:
  adaptive_dialog:
  checkbox_formfield: ^0.2.0
  multi_select_flutter: ^4.1.3
  parent_child_checkbox: ^0.0.5
  flutter_tts: ^3.7.0
  speech_to_text: ^6.3.0
  flutter_pdfview: ^1.3.1
  syncfusion_flutter_calendar: ^22.2.8
  smooth_page_indicator: ^1.1.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/default_person.png
    - assets/images/grammar.jpg
    - assets/images/images.png
    - assets/images/logo_white.png
    - assets/images/paragraphs.jpg
    - assets/images/pdf.jpg
    - assets/images/posts.png
    - assets/images/question.png
    - assets/images/sort.jpg
    - assets/images/speechtotext.png
    - assets/images/story.jpg
    - assets/images/story1.jpg
    - assets/images/text.png
    - assets/images/text1.jpg
    - assets/images/texttospeech.png
    - assets/images/translate.png
    - assets/images/translatebrown.png
    - assets/images/undraw_book_lover_re_rwjy.svg
    - assets/images/undraw_browsing_online_re_umsa.svg
    - assets/images/undraw_exams_re_4ios.svg
    - assets/images/undraw_image_viewer_re_7ejc.svg
    - assets/images/undraw_learning.svg
    - assets/images/undraw_listening_re_c2w0.svg
    - assets/images/undraw_mobile_posts_re_bpuw.svg
    - assets/images/undraw_my_answer_re_k4dv.svg
    - assets/images/undraw_online_everywhere_re_n3lr.svg
    - assets/images/undraw_online_media_re_r9qv.svg
    - assets/images/undraw_online_test_re_kyfx.svg
    - assets/images/undraw_podcast_re_wr88.svg
    - assets/images/undraw_questions_re_1fy7.svg
    - assets/images/undraw_searching_re_3ra9.svg
    - assets/images/undraw_speech_to_text_re_8mtf.svg
    - assets/images/undraw_text_files_au1q.svg
    - assets/images/video.jpg
    - assets/images/vocabulary.jpg
    - assets/in.html
    - assets/testAgora.js
    - lib/features/teachers/presentation/bloc/
    - lib/features/teachers/presentation/bloc/become_a_teacher/
    - lib/features/teachers/presentation/bloc/teacher_request_details/
    - lib/features/teachers/presentation/bloc/teachers_requests/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
